/**
 * Prompt 31 - CIBIL Real Adapter
 * TransUnion CIBIL API v2 - request/response types and adapter interface.
 * Stub throws NotImplemented; swap CIBIL_ADAPTER=real in production.
 */

// ─── Request / Response Types (TransUnion CIBIL API v2) ───────────────────────

export interface CibilAddress {
  line1: string;
  line2?: string;
  city: string;
  state: string;
  pincode: string;
  category: 'CURRENT' | 'PERMANENT' | 'OFFICE';
}

export interface CibilIdentifier {
  type: 'PAN' | 'AADHAAR' | 'VOTER_ID' | 'PASSPORT' | 'DRIVING_LICENSE';
  value: string;
}

export interface CibilPullRequest {
  /** TransUnion assigned member ID */
  memberId: string;
  /** TransUnion assigned password */
  memberPassword: string;
  /** Unique reference generated by lender for dedup */
  inquiryPurpose: 'ACCOUNT_REVIEW' | 'LOAN' | 'CREDIT_CARD' | 'PRE_SCREEN';
  pullType: 'SOFT' | 'HARD';
  applicant: {
    firstName: string;
    middleName?: string;
    lastName: string;
    dateOfBirth: string; // YYYY-MM-DD
    gender: 'M' | 'F' | 'T';
    phone: string;
    email?: string;
    identifiers: CibilIdentifier[];
    addresses: CibilAddress[];
  };
  /** Internal application reference - stored as inquiry reference */
  applicationId: string;
  /** Timestamp in ISO 8601 */
  requestedAt: string;
}

export interface CibilTradeline {
  accountNumber: string;
  subscriberName: string;
  accountType: string;
  ownershipType: string;
  dateOpened: string;
  dateClosed?: string;
  creditLimit?: number;
  highCredit?: number;
  currentBalance: number;
  amountOverdue: number;
  scheduledMonthlyPayment?: number;
  actualPaymentAmount?: number;
  paymentRating: string;
  paymentHistory: string; // 24-month string e.g. "000000000000000000000000"
  suitFiledStatus?: string;
  writtenOffStatus?: string;
}

export interface CibilEnquiry {
  subscriberName: string;
  inquiryDate: string;
  inquiryPurpose: string;
  amount?: number;
}

export interface CibilPullResponse {
  /** TransUnion control number for the report */
  controlNumber: string;
  /** Reference from CibilPullRequest.applicationId */
  applicationId: string;
  /** HTTP-level status from TU API */
  status: 'SUCCESS' | 'NO_HIT' | 'THIN_FILE' | 'ERROR';
  errorCode?: string;
  errorMessage?: string;
  report?: {
    score: number | null; // null for NO_HIT / THIN_FILE
    scoreVersion: string;
    scoreReasons: string[];
    totalAccounts: number;
    activeAccounts: number;
    closedAccounts: number;
    delinquentAccounts: number;
    totalBalance: number;
    totalOverdue: number;
    enquiriesLast30Days: number;
    enquiriesLast12Months: number;
    enquiriesLast24Months: number;
    maxDpdLast12Months: number;
    maxDpdLast24Months: number;
    hasWriteOff: boolean;
    hasSettlement: boolean;
    oldestAccountAgeMonths: number;
    tradelines: CibilTradeline[];
    enquiries: CibilEnquiry[];
    reportGeneratedAt: string;
    validUntil: string; // typically 30 days from generation
  };
  rawXml?: string; // full raw XML response from TU for archival
}

// ─── Adapter Interface ─────────────────────────────────────────────────────────

export interface ICibilAdapter {
  /**
   * Pull CIBIL report for an applicant.
   * Hard pull is recorded as an inquiry; soft pull is not.
   */
  pull(request: CibilPullRequest): Promise<CibilPullResponse>;

  /**
   * Parse the raw XML from TransUnion into a typed CibilPullResponse.
   * Useful when storing raw XML and re-parsing later.
   */
  parseResponse(rawXml: string, applicationId: string): Promise<CibilPullResponse>;
}

// ─── Real Adapter (Stub - throws NotImplemented) ───────────────────────────────

export class RealCibilAdapter implements ICibilAdapter {
  private readonly baseUrl = 'https://testtuefservice.cibil.com/tuefservice'; // prod: tuefservice.cibil.com

  async pull(_request: CibilPullRequest): Promise<CibilPullResponse> {
    throw new Error(
      'NOT_IMPLEMENTED: RealCibilAdapter.pull() requires TransUnion CIBIL API v2 credentials. ' +
        'Set CIBIL_MEMBER_ID, CIBIL_MEMBER_PASSWORD, and CIBIL_ADAPTER=real in environment.',
    );
  }

  async parseResponse(_rawXml: string, _applicationId: string): Promise<CibilPullResponse> {
    throw new Error(
      'NOT_IMPLEMENTED: RealCibilAdapter.parseResponse() requires XML parsing logic ' +
        'against the TransUnion TUEF v1.5 schema.',
    );
  }
}

// ─── Mock Adapter ──────────────────────────────────────────────────────────────

export class MockCibilAdapter implements ICibilAdapter {
  async pull(request: CibilPullRequest): Promise<CibilPullResponse> {
    const score = 720 + Math.floor(Math.random() * 100); // 720-819
    return {
      controlNumber: `TU${Date.now()}`,
      applicationId: request.applicationId,
      status: 'SUCCESS',
      report: {
        score,
        scoreVersion: '2.0',
        scoreReasons: ['LENGTH_OF_CREDIT_HISTORY', 'PAYMENT_HISTORY_ON_TIME'],
        totalAccounts: 3,
        activeAccounts: 2,
        closedAccounts: 1,
        delinquentAccounts: 0,
        totalBalance: 450000,
        totalOverdue: 0,
        enquiriesLast30Days: 1,
        enquiriesLast12Months: 2,
        enquiriesLast24Months: 3,
        maxDpdLast12Months: 0,
        maxDpdLast24Months: 0,
        hasWriteOff: false,
        hasSettlement: false,
        oldestAccountAgeMonths: 48,
        tradelines: [],
        enquiries: [],
        reportGeneratedAt: new Date().toISOString(),
        validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
    };
  }

  async parseResponse(_rawXml: string, applicationId: string): Promise<CibilPullResponse> {
    return this.pull({} as CibilPullRequest).then((r) => ({ ...r, applicationId }));
  }
}

// ─── Factory ───────────────────────────────────────────────────────────────────

export function createCibilAdapter(): ICibilAdapter {
  if (process.env.CIBIL_ADAPTER === 'real') {
    return new RealCibilAdapter();
  }
  return new MockCibilAdapter();
}
