export enum ApplicationStatus {
  LEAD = 'LEAD',
  APPLICATION = 'APPLICATION',
  DOCUMENT_COLLECTION = 'DOCUMENT_COLLECTION',
  BUREAU_CHECK = 'BUREAU_CHECK',
  UNDERWRITING = 'UNDERWRITING',
  APPROVED = 'APPROVED',
  SANCTIONED = 'SANCTIONED',
  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum LoanStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  WRITTEN_OFF = 'WRITTEN_OFF',
  RESTRUCTURED = 'RESTRUCTURED',
  FORECLOSED = 'FORECLOSED',
  SETTLED = 'SETTLED',
}

export enum PaymentStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  REVERSED = 'REVERSED',
}

export enum NpaClassification {
  STANDARD = 'STANDARD',
  SMA_0 = 'SMA_0',
  SMA_1 = 'SMA_1',
  SMA_2 = 'SMA_2',
  NPA_SUBSTANDARD = 'NPA_SUBSTANDARD',
  NPA_DOUBTFUL_1 = 'NPA_DOUBTFUL_1',
  NPA_DOUBTFUL_2 = 'NPA_DOUBTFUL_2',
  NPA_DOUBTFUL_3 = 'NPA_DOUBTFUL_3',
  NPA_LOSS = 'NPA_LOSS',
}

export enum CollectionStatus {
  NOT_DUE = 'NOT_DUE',
  DUE = 'DUE',
  OVERDUE = 'OVERDUE',
  NOTICE_SENT = 'NOTICE_SENT',
  LEGAL_PROCEEDINGS = 'LEGAL_PROCEEDINGS',
  SETTLED = 'SETTLED',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  CREDIT_OFFICER = 'CREDIT_OFFICER',
  CREDIT_HEAD = 'CREDIT_HEAD',
  OPS_OFFICER = 'OPS_OFFICER',
  COLLECTION_AGENT = 'COLLECTION_AGENT',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  ACCOUNTS_OFFICER = 'ACCOUNTS_OFFICER',
  DSA_MANAGER = 'DSA_MANAGER',
  VIEWER = 'VIEWER',
}

export enum KycStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentType {
  AADHAAR_FRONT = 'AADHAAR_FRONT',
  AADHAAR_BACK = 'AADHAAR_BACK',
  PAN_CARD = 'PAN_CARD',
  SALARY_SLIP = 'SALARY_SLIP',
  BANK_STATEMENT = 'BANK_STATEMENT',
  ITR = 'ITR',
  PHOTO = 'PHOTO',
  SIGNATURE = 'SIGNATURE',
  PROPERTY_DOC = 'PROPERTY_DOC',
  VEHICLE_RC = 'VEHICLE_RC',
  GOLD_ASSESSMENT = 'GOLD_ASSESSMENT',
  SANCTION_LETTER = 'SANCTION_LETTER',
  LOAN_AGREEMENT = 'LOAN_AGREEMENT',
  OTHER = 'OTHER',
}

export enum NotificationChannel {
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export enum LoanProductType {
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  BUSINESS_LOAN = 'BUSINESS_LOAN',
  VEHICLE_FINANCE = 'VEHICLE_FINANCE',
  LAP = 'LAP',
  HOME_LOAN = 'HOME_LOAN',
  GOLD_LOAN = 'GOLD_LOAN',
  EDUCATION_LOAN = 'EDUCATION_LOAN',
  MSME_LOAN = 'MSME_LOAN',
  SUPPLY_CHAIN_FINANCE = 'SUPPLY_CHAIN_FINANCE',
  MICROFINANCE = 'MICROFINANCE',
}

export enum RepaymentMode {
  NACH = 'NACH',
  UPI = 'UPI',
  NEFT = 'NEFT',
  RTGS = 'RTGS',
  CASH = 'CASH',
  CHEQUE = 'CHEQUE',
  ONLINE = 'ONLINE',
  DEMAND_DRAFT = 'DEMAND_DRAFT',
}

export enum SourceType {
  DSA = 'DSA',
  BRANCH = 'BRANCH',
  WEB = 'WEB',
  MOBILE_APP = 'MOBILE_APP',
  API = 'API',
  WALKIN = 'WALKIN',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum CustomerType {
  INDIVIDUAL = 'INDIVIDUAL',
  PROPRIETORSHIP = 'PROPRIETORSHIP',
  PARTNERSHIP = 'PARTNERSHIP',
  PRIVATE_LIMITED = 'PRIVATE_LIMITED',
  PUBLIC_LIMITED = 'PUBLIC_LIMITED',
  LLP = 'LLP',
  HUF = 'HUF',
  TRUST = 'TRUST',
}

export enum EmploymentType {
  SALARIED = 'SALARIED',
  SELF_EMPLOYED_PROFESSIONAL = 'SELF_EMPLOYED_PROFESSIONAL',
  SELF_EMPLOYED_BUSINESS = 'SELF_EMPLOYED_BUSINESS',
  RETIRED = 'RETIRED',
  HOMEMAKER = 'HOMEMAKER',
  STUDENT = 'STUDENT',
  UNEMPLOYED = 'UNEMPLOYED',
}

export enum ScheduleStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
}
