#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ec2-user-data.sh — Cloud-init bootstrap for BankOS on Amazon Linux 2023
#
# Runs as root on first boot.  Everything is logged to /var/log/bankos-init.log
# so you can ssh in and tail that file to watch progress.
#
# Steps:
#   1. System updates + install Docker, Docker Compose plugin, git
#   2. Start Docker daemon, add ec2-user to docker group
#   3. Clone the BankOS repository
#   4. Generate secure DB / JWT secrets
#   5. Write /opt/bankos/.env.prod
#   6. Build images and start docker-compose.prod.yml
#   7. Run prisma migrate deploy + prisma db seed
#   8. Enable auto-restart via systemd on reboot
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

LOG="/var/log/bankos-init.log"
exec > >(tee -a "$LOG") 2>&1

echo "════════════════════════════════════════════════════"
echo " BankOS user-data bootstrap starting at $(date -u)"
echo "════════════════════════════════════════════════════"

# ── Config — override by editing before launching or via Instance metadata ────
REPO_URL="${BANKOS_REPO:-https://github.com/gs1231231/nbfc500.git}"
REPO_BRANCH="${BANKOS_BRANCH:-main}"
APP_DIR="/opt/bankos"
COMPOSE_FILE="docker-compose.prod.yml"

# ── 1. System update and package installation ─────────────────────────────────
echo "[1/8] Updating system packages ..."
dnf update -y --quiet

echo "[1/8] Installing Docker and git ..."
dnf install -y docker git jq openssl

# Docker Compose v2 plugin
COMPOSE_VERSION="v2.27.1"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

echo "[1/8] Docker $(docker --version) — Compose $(docker compose version)"

# ── 2. Start Docker ───────────────────────────────────────────────────────────
echo "[2/8] Enabling and starting Docker daemon ..."
systemctl enable --now docker
usermod -aG docker ec2-user

# ── 3. Clone repository ───────────────────────────────────────────────────────
echo "[3/8] Cloning $REPO_URL (branch: $REPO_BRANCH) into $APP_DIR ..."
mkdir -p "$APP_DIR"
if [[ -d "$APP_DIR/.git" ]]; then
  echo "      Repository already exists — pulling latest ..."
  git -C "$APP_DIR" fetch origin
  git -C "$APP_DIR" reset --hard "origin/$REPO_BRANCH"
else
  git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$APP_DIR"
fi
chown -R ec2-user:ec2-user "$APP_DIR"

# ── 4. Generate secrets ───────────────────────────────────────────────────────
echo "[4/8] Generating secure credentials ..."
DB_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=\n' | head -c 40)
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=\n' | head -c 64)
JWT_REFRESH_SECRET=$(openssl rand -base64 48 | tr -d '/+=\n' | head -c 64)

# ── 5. Write .env.prod ────────────────────────────────────────────────────────
echo "[5/8] Writing $APP_DIR/.env.prod ..."

# Detect the public IP from EC2 instance metadata (IMDSv2)
TOKEN=$(curl -s -X PUT \
  "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || true)
PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  "http://169.254.169.254/latest/meta-data/public-ipv4" 2>/dev/null || echo "localhost")

cat > "$APP_DIR/.env.prod" <<ENV
# ── BankOS Production Environment ──────────────────────────────────────────
# Generated by ec2-user-data.sh on $(date -u)
# Edit this file and restart containers if you need to change values.

# ── Server ─────────────────────────────────────────────────────────────────
NODE_ENV=production
PUBLIC_DOMAIN=http://${PUBLIC_IP}
IMAGE_TAG=latest
LOG_LEVEL=info

# ── Database ────────────────────────────────────────────────────────────────
DB_PASSWORD=${DB_PASSWORD}

# ── JWT ─────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

# ── CORS ────────────────────────────────────────────────────────────────────
# Comma-separated list of allowed origins (leave empty to disable CORS)
CORS_ORIGINS=

# ── Organisation ────────────────────────────────────────────────────────────
ORG_ID=bankos

# ── Bureau APIs ─────────────────────────────────────────────────────────────
EQUIFAX_API_KEY=
EQUIFAX_API_URL=
CIBIL_API_KEY=
CIBIL_API_URL=
EXPERIAN_API_KEY=
EXPERIAN_API_URL=

# ── Notifications ────────────────────────────────────────────────────────────
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@bankos.in
SMS_API_KEY=
SMS_SENDER_ID=BANKOS

# ── Payment gateway ──────────────────────────────────────────────────────────
PAYMENT_GATEWAY_URL=
PAYMENT_GATEWAY_KEY=
ENV

chmod 600 "$APP_DIR/.env.prod"
chown ec2-user:ec2-user "$APP_DIR/.env.prod"
echo "      .env.prod written (secrets NOT logged)"

# ── 6. Build and start containers ────────────────────────────────────────────
echo "[6/8] Building Docker images and starting services ..."
cd "$APP_DIR"

# Enable Next.js standalone output before building the web portal image.
# Patch next.config.mjs if it does not already contain output: 'standalone'.
NEXT_CONFIG="$APP_DIR/apps/web-portal/next.config.mjs"
if ! grep -q "standalone" "$NEXT_CONFIG"; then
  echo "      Patching next.config.mjs to enable standalone output ..."
  cat > "$NEXT_CONFIG" <<'NEXTCFG'
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
};
export default nextConfig;
NEXTCFG
fi

# Run compose as ec2-user (who is now in the docker group)
# We source .env.prod so all variables are available to compose
set -o allexport
# shellcheck source=/dev/null
source "$APP_DIR/.env.prod"
set +o allexport

docker compose \
  --env-file "$APP_DIR/.env.prod" \
  -f "$APP_DIR/$COMPOSE_FILE" \
  build --no-cache --parallel

docker compose \
  --env-file "$APP_DIR/.env.prod" \
  -f "$APP_DIR/$COMPOSE_FILE" \
  up -d

echo "      Containers started. Waiting 20 s for postgres to initialise ..."
sleep 20

# ── 7. Prisma migrate + seed ──────────────────────────────────────────────────
echo "[7/8] Running prisma migrate deploy ..."
docker compose \
  --env-file "$APP_DIR/.env.prod" \
  -f "$APP_DIR/$COMPOSE_FILE" \
  exec -T api-gateway \
  node_modules/.bin/prisma migrate deploy \
    --schema=libs/database/prisma/schema.prisma \
  || echo "      WARNING: prisma migrate failed — check logs"

echo "[7/8] Running prisma db seed ..."
docker compose \
  --env-file "$APP_DIR/.env.prod" \
  -f "$APP_DIR/$COMPOSE_FILE" \
  exec -T api-gateway \
  node_modules/.bin/ts-node libs/database/prisma/seed.ts \
  || echo "      WARNING: seed failed — may already be seeded, check logs"

# ── 8. Systemd service for auto-restart on reboot ────────────────────────────
echo "[8/8] Installing bankos-docker systemd service ..."
cat > /etc/systemd/system/bankos-docker.service <<SERVICE
[Unit]
Description=BankOS Docker Compose
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env.prod
ExecStart=/usr/local/lib/docker/cli-plugins/docker-compose \\
    --env-file ${APP_DIR}/.env.prod \\
    -f ${APP_DIR}/${COMPOSE_FILE} \\
    up -d --remove-orphans
ExecStop=/usr/local/lib/docker/cli-plugins/docker-compose \\
    --env-file ${APP_DIR}/.env.prod \\
    -f ${APP_DIR}/${COMPOSE_FILE} \\
    down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable bankos-docker.service

echo ""
echo "════════════════════════════════════════════════════"
echo " BankOS bootstrap complete at $(date -u)"
echo ""
echo " Public IP   : ${PUBLIC_IP}"
echo " Web portal  : http://${PUBLIC_IP}/"
echo " API         : http://${PUBLIC_IP}/api/v1/"
echo " Swagger     : http://${PUBLIC_IP}/api/docs"
echo ""
echo " DB password and JWT secrets are in:"
echo "   ${APP_DIR}/.env.prod"
echo ""
echo " To view logs:"
echo "   docker compose -f ${APP_DIR}/${COMPOSE_FILE} logs -f"
echo "════════════════════════════════════════════════════"
