import {
  Body,
  Controller,
  Get,
  Headers,
  HttpCode,
  HttpStatus,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiHeader,
  ApiOkResponse,
  ApiOperation,
  ApiQuery,
  ApiTags,
} from '@nestjs/swagger';
import {
  NotificationService,
  NotificationResult,
} from './notification.service';
import { SendNotificationDto } from './dto/notification.dto';

/**
 * NotificationController — HTTP interface for the notification service.
 *
 * All endpoints require X-Organization-Id to identify the tenant.
 *
 * Base path: /api/v1/notifications
 */
@ApiTags('Notifications')
@ApiHeader({
  name: 'X-Organization-Id',
  description: 'Tenant organization UUID (injected by API Gateway)',
  required: true,
  example: '550e8400-e29b-41d4-a716-446655440001',
})
@Controller('api/v1/notifications')
export class NotificationController {
  constructor(private readonly notificationService: NotificationService) {}

  /**
   * POST /api/v1/notifications/send
   *
   * Send a notification to a customer via SMS, Email, or WhatsApp.
   * The message is generated by interpolating the specified template with
   * the provided variables. DND restrictions apply for SMS and WhatsApp.
   */
  @Post('send')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Send a notification',
    description:
      'Send a templated notification to a customer. Channels: SMS, EMAIL, WHATSAPP. ' +
      'DND is enforced for SMS and WhatsApp (no messages between 9 PM and 8 AM IST). ' +
      'All channel adapters are mock — messages are logged to console.',
  })
  @ApiOkResponse({ description: 'Notification dispatched (or blocked by DND)' })
  async sendNotification(
    @Headers('x-organization-id') orgId: string,
    @Body() dto: SendNotificationDto,
  ): Promise<{
    success: boolean;
    data: NotificationResult;
  }> {
    const result = await this.notificationService.sendNotification(
      orgId,
      dto.customerId,
      dto.channel,
      dto.templateCode,
      dto.variables ?? {},
    );

    return {
      success: true,
      data: result,
    };
  }

  /**
   * GET /api/v1/notifications?customerId=X
   *
   * Retrieve notification history for a customer.
   * Returns an empty array for MVP (placeholder for future DB-backed log).
   */
  @Get()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Get notification history',
    description:
      'Returns the notification history for a customer. ' +
      'Currently returns an empty array (MVP placeholder — no notification log table yet).',
  })
  @ApiQuery({
    name: 'customerId',
    description: 'UUID of the customer',
    required: true,
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @ApiOkResponse({ description: 'Notification history (empty for MVP)' })
  async getHistory(
    @Headers('x-organization-id') orgId: string,
    @Query('customerId') customerId: string,
  ): Promise<{
    success: boolean;
    data: NotificationResult[];
  }> {
    const data = await this.notificationService.getHistory(orgId, customerId);
    return { success: true, data };
  }
}
